<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/clase_8_outliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
import numpy as np

#Diccionario con datos mixtos
datos = {
"Cliente": [f"CL{1:03}" for i in range(1, 51)],
"Consumo_kwh": np.append(np.random.normal (350, 40, 45).round(1), [200, 215, 700, 720, 750])
}

df = pd.DataFrame(datos)
df

   Cliente  Consumo_kwh
0    CL001        314.6
1    CL001        309.6
2    CL001        375.0
3    CL001        250.4
4    CL001        275.8
5    CL001        379.8
6    CL001        325.5
7    CL001        325.0
8    CL001        393.2
9    CL001        322.1
10   CL001        406.1
11   CL001        340.4
12   CL001        396.4
13   CL001        380.3
14   CL001        303.2
15   CL001        344.8
16   CL001        301.8
17   CL001        309.2
18   CL001        351.7
19   CL001        367.5
20   CL001        393.9
21   CL001        375.9
22   CL001        328.7
23   CL001        318.9
24   CL001        366.0
25   CL001        301.1
26   CL001        327.1
27   CL001        339.1
28   CL001        360.9
29   CL001        357.3
30   CL001        309.9
31   CL001        246.8
32   CL001        315.1
33   CL001        354.9
34   CL001        428.5
35   CL001        350.3
36   CL001        300.8
37   CL001        369.6
38   CL001        417.1
39   CL001        301.7
40   CL001        318.8
41   CL001        323.2
42   CL001        322.7
43   CL001        326.7
44   CL001        342.6
45   CL001        200.0
46   CL001        215.0
47   CL001        700.0
48   CL001        720.0
49   CL001        750.0

In [34]:
df

   Cliente  Consumo_kwh
0    CL001        314.6
1    CL001        309.6
2    CL001        375.0
3    CL001        250.4
4    CL001        275.8
5    CL001        379.8
6    CL001        325.5
7    CL001        325.0
8    CL001        393.2
9    CL001        322.1
10   CL001        406.1
11   CL001        340.4
12   CL001        396.4
13   CL001        380.3
14   CL001        303.2
15   CL001        344.8
16   CL001        301.8
17   CL001        309.2
18   CL001        351.7
19   CL001        367.5
20   CL001        393.9
21   CL001        375.9
22   CL001        328.7
23   CL001        318.9
24   CL001        366.0
25   CL001        301.1
26   CL001        327.1
27   CL001        339.1
28   CL001        360.9
29   CL001        357.3
30   CL001        309.9
31   CL001        246.8
32   CL001        315.1
33   CL001        354.9
34   CL001        428.5
35   CL001        350.3
36   CL001        300.8
37   CL001        369.6
38   CL001        417.1
39   CL001        301.7
40   CL001        318.8
41   CL001        323.2
42   CL001        322.7
43   CL001        326.7
44   CL001        342.6
45   CL001        200.0
46   CL001        215.0
47   CL001        700.0
48   CL001        720.0
49   CL001        750.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Cliente      50 non-null     object
 1   Consumo_kwh  50 non-null     float64
dtypes: float64(1), object(1)
memory usage: 932.0+ bytes

In [36]:
df.describe()

       Consumo_kwh
count    50.000000
mean    357.100000
std     104.387627
min     200.000000
25%     311.075000
50%     333.900000
75%     373.650000
max     750.000000

In [37]:
# Calcular los cuartiles para aplicar el metodo IQR para identificaciónde datos atipicos.
q1 = df['Consumo_kwh'].quantile(0.25)
q3 = df['Consumo_kwh'].quantile(0.75)

IQR = q3 - q1
IQR

np.float64(62.57499999999999)

In [38]:
# Limites para detectar Outliers
limite_inferior = q1 - 1.5 * IQR
limite_superior = q3 + 1.5 * IQR

print(f"Limite Inferior: {limite_inferior}")
print(f"Limite Superior: {limite_superior}")
print("Q1:", q1)
print("Q3:", q3)
#

Limite Inferior: 217.2125
Limite Superior: 467.51249999999993
Q1: 311.075
Q3: 373.65

In [39]:
# DETECTAR VALORES FUERA DE RANGO
Outliers = df[(df['Consumo_kwh'] < limite_inferior) | (df['Consumo_kwh'] > limite_superior)]
print("Cantidad de Outliers:")
Outliers

Cantidad de Outliers:

   Cliente  Consumo_kwh
45   CL001        200.0
46   CL001        215.0
47   CL001        700.0
48   CL001        720.0
49   CL001        750.0

## ACTIVIDAD PARA MANEJO DE OUTLIERS

In [40]:
# Cargar el dataframe
df_criminal = pd.read_csv('/content/datos_criminalidad_actualizado.csv')
df_criminal

,id_caso,fecha,municipio,estrato,tipo_delito,edad_victima,tiempo_respuesta,numero_victimas,arma_utilizada,gravedad
0,1,2021-02-02,Manizales,2.0,Lesiones personales,29.0,20.0,2,ninguna,baja
1,2,2022-03-03,Ibagué,3.0,fraude,42.0,37.0,3,Arma de fuego,Grave
2,3,2023-04-04,Pereira,4.0,Violencia intrafamiliar,55.0,54.0,4,NaN,Media
3,4,2024-05-05,Soacha,5.0,Amenazas,68.0,71.0,1,No reportada,MEDIA
4,5,2025-06-06,Bucaramanga,6.0,Hurto,81.0,88.0,2,Arma blanca,Leve
...,...,...,...,...,...,...,...,...,...,...
195,196,01/05/2024,Manizales,5.0,Lesiones personales,48.0,NaN,1,No reportada,MEDIA
196,197,2025-06-02,Ibagué,6.0,fraude,61.0,84.0,2,Arma blanca,Leve
197,197,2020-07-03,Pereira,1.0,Violencia intrafamiliar,74.0,15.0,NaN,Sin dato,Alta
198,199,2021-08-04,Soacha,2.0,Amenazas,19.0,32.0,4,Objeto contundente,alta
199,200,2022-09-05,Bucaramanga,3.0,Hurto,32.0,49.0,1,Ninguna,Baja

In [41]:
df_criminal.head()

,id_caso,fecha,municipio,estrato,tipo_delito,edad_victima,tiempo_respuesta,numero_victimas,arma_utilizada,gravedad
0,1,2021-02-02,Manizales,2.0,Lesiones personales,29.0,20.0,2,ninguna,baja
1,2,2022-03-03,Ibagué,3.0,fraude,42.0,37.0,3,Arma de fuego,Grave
2,3,2023-04-04,Pereira,4.0,Violencia intrafamiliar,55.0,54.0,4,NaN,Media
3,4,2024-05-05,Soacha,5.0,Amenazas,68.0,71.0,1,No reportada,MEDIA
4,5,2025-06-06,Bucaramanga,6.0,Hurto,81.0,88.0,2,Arma blanca,Leve

In [42]:
df_criminal.tail()

,id_caso,fecha,municipio,estrato,tipo_delito,edad_victima,tiempo_respuesta,numero_victimas,arma_utilizada,gravedad
195,196,01/05/2024,Manizales,5.0,Lesiones personales,48.0,NaN,1,No reportada,MEDIA
196,197,2025-06-02,Ibagué,6.0,fraude,61.0,84.0,2,Arma blanca,Leve
197,197,2020-07-03,Pereira,1.0,Violencia intrafamiliar,74.0,15.0,NaN,Sin dato,Alta
198,199,2021-08-04,Soacha,2.0,Amenazas,19.0,32.0,4,Objeto contundente,alta
199,200,2022-09-05,Bucaramanga,3.0,Hurto,32.0,49.0,1,Ninguna,Baja

In [43]:
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         192 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       191 non-null    object
 5   edad_victima      188 non-null    float64
 6   tiempo_respuesta  186 non-null    float64
 7   numero_victimas   189 non-null    object
 8   arma_utilizada    175 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 15.8+ KB

In [44]:
df_criminal.describe()

          id_caso     estrato  edad_victima  tiempo_respuesta
count  200.000000  189.000000    188.000000        186.000000
mean   100.470000    3.476190     51.686170         80.532258
std     57.871623    1.712195     25.804746        158.555580
min      1.000000    1.000000     -4.000000          3.000000
25%     50.750000    2.000000     32.750000         26.000000
50%    100.500000    3.000000     51.000000         49.000000
75%    150.250000    5.000000     69.000000         71.000000
max    200.000000    6.000000    142.000000        999.000000

In [45]:
# contar los valores nulos por columna
df_criminal.isnull().sum()

id_caso              0
fecha               10
municipio            8
estrato             11
tipo_delito          9
edad_victima        12
tiempo_respuesta    14
numero_victimas     11
arma_utilizada      25
gravedad             0
dtype: int64

In [46]:
# contar la totalidad de los valores nulos del dataframe
df_criminal.isnull().sum().sum()

np.int64(100)

In [47]:
# No se recomienda realizar la eliminación de los datos, ya que supera el 5% del total de datos de dataframe. Por ende, vamos a remplazar los datos de cada columna con la mediana,media y moda.

# Vamos a remplazar la columna municipio con la moda.
df_criminal['municipio'].fillna(df_criminal['municipio'].mode()[0], inplace=True)

df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       191 non-null    object
 5   edad_victima      188 non-null    float64
 6   tiempo_respuesta  186 non-null    float64
 7   numero_victimas   189 non-null    object
 8   arma_utilizada    175 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 15.8+ KB

/tmp/ipykernel_885/3251676310.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_criminal['municipio'].fillna(df_criminal['municipio'].mode()[0], inplace=True)

In [48]:
# vamos a remplazar los valores nullos de la columna arma_utilizada con la moda
df_criminal['arma_utilizada'].fillna(df_criminal['arma_utilizada'].mode()[0], inplace=True)
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       191 non-null    object
 5   edad_victima      188 non-null    float64
 6   tiempo_respuesta  186 non-null    float64
 7   numero_victimas   189 non-null    object
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 15.8+ KB

/tmp/ipykernel_885/1803348701.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_criminal['arma_utilizada'].fillna(df_criminal['arma_utilizada'].mode()[0], inplace=True)

In [49]:
# Primero convertimos 'numero_victimas' a tipo numérico para poder calcular el promedio
df_criminal['numero_victimas'] = pd.to_numeric(df_criminal['numero_victimas'], errors='coerce')

# Ahora reemplazamos los valores nulos con el promedio de cada columna
df_criminal['tiempo_respuesta'].fillna(df_criminal['tiempo_respuesta'].mean(), inplace=True)
df_criminal['numero_victimas'].fillna(df_criminal['numero_victimas'].mean(), inplace=True)

df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       191 non-null    object
 5   edad_victima      188 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

/tmp/ipykernel_885/123169516.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_criminal['tiempo_respuesta'].fillna(df_criminal['tiempo_respuesta'].mean(), inplace=True)
/tmp/ipykernel_885/123169516.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_criminal['numero_victimas'].fillna(df_criminal['numero_victimas'].mean(), inplace=True)

In [50]:
df_criminal.isnull().sum()

id_caso              0
fecha               10
municipio            0
estrato             11
tipo_delito          9
edad_victima        12
tiempo_respuesta     0
numero_victimas      0
arma_utilizada       0
gravedad             0
dtype: int64

In [51]:
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       191 non-null    object
 5   edad_victima      188 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

In [52]:
# Vamos a tratar los valores nulos de la columna edad victima con la moda
df_criminal['edad_victima'].fillna(df_criminal['edad_victima'].mode()[0], inplace=True)
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       191 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

/tmp/ipykernel_885/3489147703.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_criminal['edad_victima'].fillna(df_criminal['edad_victima'].mode()[0], inplace=True)

In [53]:
# vamos a tratar los datos nulos de la columna tipo_delito con la moda (ya que es categórica)
df_criminal['tipo_delito'] = df_criminal['tipo_delito'].fillna(df_criminal['tipo_delito'].mode()[0])
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             190 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

In [54]:
# vamos a tratar los datos nulos de la columna fecha con la moda
df_criminal['fecha'] = df_criminal['fecha'].fillna(df_criminal['fecha'].mode()[0])
df_criminal.info()
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           189 non-null    float64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

In [55]:
# vamos a tratar los datos nulos de la columna estrato con la moda
df_criminal['estrato'] = df_criminal['estrato'].fillna(df_criminal['estrato'].mode()[0])
df_criminal.info()
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           200 non-null    float64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_utilizada    200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

In [56]:
df_criminal.isnull().sum()

id_caso             0
fecha               0
municipio           0
estrato             0
tipo_delito         0
edad_victima        0
tiempo_respuesta    0
numero_victimas     0
arma_utilizada      0
gravedad            0
dtype: int64

In [57]:
# Vamos a realizar el manejo de datos atipicos
## Calcular los cuartiles para aplicar el metodo IQR para identificaciónde datos atipicos para la columna número de victimas.
q1 = df_criminal['numero_victimas'].quantile(0.25)
q3 = df_criminal['numero_victimas'].quantile(0.75)

IQR = q3 - q1
IQR

np.float64(1.0)

In [58]:
# Limites para detectar Outliers
limite_inferior = q1 - 1.5 * IQR
limite_superior = q3 + 1.5 * IQR

print(f"Limite Inferior: {limite_inferior}")
print(f"Limite Superior: {limite_superior}")
print("Q1:", q1)
print("Q3:", q3)
#

Limite Inferior: 0.5
Limite Superior: 4.5
Q1: 2.0
Q3: 3.0

In [59]:
# DETECTAR VALORES FUERA DE RANGO
Outliers = df_criminal[(df_criminal['numero_victimas'] < limite_inferior) | (df_criminal['numero_victimas'] > limite_superior)]
print("Cantidad de Outliers:")
Outliers

#NO SE PRESENTARON  VALORES ATIPICOS PARA LA COLUMNA NÚMERO DE VICTIMAS. TODOS SE ENCUENTRAN DENTRO DE LOS LIMITES INFERIORES Y SUPERIORES.
# NOTA: ESTO PUEDE ESTAR ASOCIADO A QUE SE REALIZO EL TRATAMIENTO DE LOS VALORES NULOS, LOS CUALES SE ENCUENTRAN DENTRO DEL RANGO POR LA MODA, MEDIANA O MEDIA.

Cantidad de Outliers:

,id_caso,fecha,municipio,estrato,tipo_delito,edad_victima,tiempo_respuesta,numero_victimas,arma_utilizada,gravedad
28,29,2025-06-02,Cúcuta,6.0,Amenazas,53.0,66.0,0.0,Arma blanca,Leve
57,58,2024-11-03,Medellín,5.0,Violencia intrafamiliar,22.0,43.0,0.0,Arma de fuego,Grave
86,87,2023-04-04,Santa Marta,4.0,fraude,59.0,20.0,0.0,Objeto contundente,alta
115,116,2022-09-05,Cali,3.0,Lesiones personales,28.0,83.0,0.0,No reportada,MEDIA
144,145,2021-02-06,bogota,2.0,Hurto,65.0,60.0,0.0,ninguna,baja
173,174,2020-07-07,Barranquilla,1.0,Amenazas,34.0,37.0,0.0,Sin dato,Alta

In [60]:
# VAMOS A RENOMBRAR NOMBRES DE COLUMNAS arma_utilizada
df_criminal.rename(columns={'arma_utilizada': 'arma_usada'}, inplace=True)
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           200 non-null    float64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_usada        200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

In [61]:
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           200 non-null    float64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_usada        200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 15.8+ KB

In [62]:
# VAMOS A REALIZAR EL CAMBIO DE TIPO DE DATO PARA LA COLUMNA ESTRATO A TIPO ENTERO
df_criminal["estrato"] = df_criminal["estrato"].astype(int)
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           200 non-null    int64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    float64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_usada        200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(3), int64(2), object(5)
memory usage: 15.8+ KB

In [63]:
# VAMOS A REALIZAR EL CAMBIO DE DATO PARA LA COLUMNA EDAD POR TIPO ENTERO
df_criminal["edad_victima"] = df_criminal["edad_victima"].astype(int)
df_criminal.info()
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           200 non-null    int64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    int64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    float64
 8   arma_usada        200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(2), int64(3), object(5)
memory usage: 15.8+ KB

In [64]:
df_criminal

,id_caso,fecha,municipio,estrato,tipo_delito,edad_victima,tiempo_respuesta,numero_victimas,arma_usada,gravedad
0,1,2021-02-02,Manizales,2,Lesiones personales,29,20.000000,2.000000,ninguna,baja
1,2,2022-03-03,Ibagué,3,fraude,42,37.000000,3.000000,Arma de fuego,Grave
2,3,2023-04-04,Pereira,4,Violencia intrafamiliar,55,54.000000,4.000000,Arma blanca,Media
3,4,2024-05-05,Soacha,5,Amenazas,68,71.000000,1.000000,No reportada,MEDIA
4,5,2025-06-06,Bucaramanga,6,Hurto,81,88.000000,2.000000,Arma blanca,Leve
...,...,...,...,...,...,...,...,...,...,...
195,196,01/05/2024,Manizales,5,Lesiones personales,48,80.532258,1.000000,No reportada,MEDIA
196,197,2025-06-02,Ibagué,6,fraude,61,84.000000,2.000000,Arma blanca,Leve
197,197,2020-07-03,Pereira,1,Violencia intrafamiliar,74,15.000000,2.431034,Sin dato,Alta
198,199,2021-08-04,Soacha,2,Amenazas,19,32.000000,4.000000,Objeto contundente,alta
199,200,2022-09-05,Bucaramanga,3,Hurto,32,49.000000,1.000000,Ninguna,Baja

In [65]:
# VAMOS A CAMBIAR EL TIPO DE DATO PARA LA COLUMNA NÚMERO DE VICTIMAS
df_criminal["numero_victimas"] = df_criminal["numero_victimas"].astype(int)
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    object
 2   municipio         200 non-null    object
 3   estrato           200 non-null    int64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    int64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    int64
 8   arma_usada        200 non-null    object
 9   gravedad          200 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 15.8+ KB

In [68]:
# VAMOS A CAMBIAR EL TIPO DE DATO PARA LA COLUMNA fecha por FECHA usando format='mixed'
df_criminal["fecha"] = pd.to_datetime(df_criminal["fecha"], format='mixed')
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_caso           200 non-null    int64
 1   fecha             200 non-null    datetime64[ns]
 2   municipio         200 non-null    object
 3   estrato           200 non-null    int64
 4   tipo_delito       200 non-null    object
 5   edad_victima      200 non-null    int64
 6   tiempo_respuesta  200 non-null    float64
 7   numero_victimas   200 non-null    int64
 8   arma_usada        200 non-null    object
 9   gravedad          200 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 15.8+ KB

In [70]:
# VAMOS A ELIMINAR COLUMNAS QUE NO APORTAN VALOR AL DATAFRAME POR EJEMPLO ID_CASO
df_criminal.drop(columns=['id_caso'], inplace=True)
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha             200 non-null    datetime64[ns]
 1   municipio         200 non-null    object
 2   estrato           200 non-null    int64
 3   tipo_delito       200 non-null    object
 4   edad_victima      200 non-null    int64
 5   tiempo_respuesta  200 non-null    float64
 6   numero_victimas   200 non-null    int64
 7   arma_usada        200 non-null    object
 8   gravedad          200 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 14.2+ KB

In [72]:
# VAMOS A CREAR UNA NUEVA COLUMNA EN EL DATAFRAME LLAMADA: CLASIFICACIÓN DEL TIPO DE DELITO.
# Usamos np.where para clasificar de manera dinámica según la columna 'gravedad'
import numpy as np

# Estandarizamos temporalmente la gravedad a minúsculas para facilitar la comparación
gravedad_lower = df_criminal['gravedad'].str.lower()

df_criminal["Clasificacion_delito"] = np.where(
    gravedad_lower.isin(['grave', 'alta']),
    "Grave",
    "No Grave"
)

df_criminal[['gravedad', 'Clasificacion_delito']].head(10)

  gravedad Clasificacion_delito
0     baja             No Grave
1    Grave                Grave
2    Media             No Grave
3    MEDIA             No Grave
4     Leve             No Grave
5     Alta                Grave
6     alta                Grave
7     Baja             No Grave
8     baja             No Grave
9    Grave                Grave

In [73]:
df_criminal

,fecha,municipio,estrato,tipo_delito,edad_victima,tiempo_respuesta,numero_victimas,arma_usada,gravedad,Clasificacion_delito
0,2021-02-02,Manizales,2,Lesiones personales,29,20.000000,2,ninguna,baja,No Grave
1,2022-03-03,Ibagué,3,fraude,42,37.000000,3,Arma de fuego,Grave,Grave
2,2023-04-04,Pereira,4,Violencia intrafamiliar,55,54.000000,4,Arma blanca,Media,No Grave
3,2024-05-05,Soacha,5,Amenazas,68,71.000000,1,No reportada,MEDIA,No Grave
4,2025-06-06,Bucaramanga,6,Hurto,81,88.000000,2,Arma blanca,Leve,No Grave
...,...,...,...,...,...,...,...,...,...,...
195,2024-01-05,Manizales,5,Lesiones personales,48,80.532258,1,No reportada,MEDIA,No Grave
196,2025-06-02,Ibagué,6,fraude,61,84.000000,2,Arma blanca,Leve,No Grave
197,2020-07-03,Pereira,1,Violencia intrafamiliar,74,15.000000,2,Sin dato,Alta,Grave
198,2021-08-04,Soacha,2,Amenazas,19,32.000000,4,Objeto contundente,alta,Grave
199,2022-09-05,Bucaramanga,3,Hurto,32,49.000000,1,Ninguna,Baja,No Grave