<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/manejando_datos_nulos_clase7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# cargar dataframe
df= pd.read_csv("/content/poblacion.txt")

In [3]:
df

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2358330.0,71.0
1,Amalfi,5376,POINT (-75.3433 6.6311),NORDESTE,4,NaN,Suicidios,Poblacion total,NaN,37.0
2,Medellín,5343,NaN,VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,1502942.0,NaN
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1467689.0,52.0
4,NaN,5921,POINT (-75.2021 6.4843),OCCIDENTE,6,2012.0,Suicidios,Poblacion total,2057555.0,1.0
...,...,...,...,...,...,...,...,...,...,...
95,Medellín,5500,POINT (-75.5873 6.5806),VALLE DE ABURRA,1,2013.0,Suicidios,Poblacion total,NaN,31.0
96,Caldas,5322,POINT (-75.2500 6.7737),VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,206615.0,NaN
97,Bello,5282,POINT (-75.1130 6.3983),VALLE DE ABURRA,1,2007.0,Suicidios,Poblacion total,561723.0,44.0
98,Abriaquí,5269,NaN,OCCIDENTE,6,2005.0,Suicidios,Poblacion total,1013727.0,107.0
99,Apartadó,5847,POINT (-75.3032 6.9436),URABA,9,2018.0,Suicidios,Poblacion total,542659.0,28.0

In [4]:
#  eliminar las filas con datos nulos
df_sin_datos_nulos = df.dropna()
df_sin_datos_nulos

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2358330.0,71.0
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1467689.0,52.0
5,Bello,5848,POINT (-75.8892 6.7863),VALLE DE ABURRA,1,2018.0,Suicidios,Poblacion total,1404107.0,39.0
8,Bello,5838,POINT (-75.9154 6.6056),VALLE DE ABURRA,1,2009.0,Suicidios,Poblacion total,491570.0,103.0
10,Apartadó,5135,POINT (-75.4242 6.5636),URABA,9,2011.0,Suicidios,Poblacion total,975548.0,142.0
...,...,...,...,...,...,...,...,...,...,...
92,Abriaquí,5740,POINT (-75.3343 6.6136),OCCIDENTE,6,2013.0,Suicidios,Poblacion total,1738857.0,72.0
93,Amalfi,5374,POINT (-75.8009 6.7667),NORDESTE,4,2016.0,Suicidios,Poblacion total,1550459.0,101.0
94,Abejorral,5180,POINT (-75.6895 6.3708),ORIENTE,7,2019.0,Suicidios,Poblacion total,701983.0,82.0
97,Bello,5282,POINT (-75.1130 6.3983),VALLE DE ABURRA,1,2007.0,Suicidios,Poblacion total,561723.0,44.0
99,Apartadó,5847,POINT (-75.3032 6.9436),URABA,9,2018.0,Suicidios,Poblacion total,542659.0,28.0

In [5]:
# eliminar columnas con almenos un dato nulo
df_sin_columnas_nulas = df.dropna(axis=1)
df_sin_columnas_nulas
#

,CodigoMunicipio,NombreRegion,CodigoRegion,CausaMortalidad,TipoPoblacionObjetivo
0,5566,URABA,9,Suicidios,Poblacion total
1,5376,NORDESTE,4,Suicidios,Poblacion total
2,5343,VALLE DE ABURRA,1,Suicidios,Poblacion total
3,5466,SUROESTE,8,Suicidios,Poblacion total
4,5921,OCCIDENTE,6,Suicidios,Poblacion total
...,...,...,...,...,...
95,5500,VALLE DE ABURRA,1,Suicidios,Poblacion total
96,5322,VALLE DE ABURRA,1,Suicidios,Poblacion total
97,5282,VALLE DE ABURRA,1,Suicidios,Poblacion total
98,5269,OCCIDENTE,6,Suicidios,Poblacion total
99,5847,URABA,9,Suicidios,Poblacion total

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          96 non-null     object
 1   CodigoMunicipio          100 non-null    int64
 2   Ubicación                94 non-null     object
 3   NombreRegion             100 non-null    object
 4   CodigoRegion             100 non-null    int64
 5   Anio                     96 non-null     float64
 6   CausaMortalidad          100 non-null    object
 7   TipoPoblacionObjetivo    100 non-null    object
 8   NumeroPoblacionObjetivo  95 non-null     float64
 9   NumeroCasos              91 non-null     float64
dtypes: float64(3), int64(2), object(5)
memory usage: 7.9+ KB

In [6]:
df_sin_columnas_nulas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CodigoMunicipio        100 non-null    int64
 1   NombreRegion           100 non-null    object
 2   CodigoRegion           100 non-null    int64
 3   CausaMortalidad        100 non-null    object
 4   TipoPoblacionObjetivo  100 non-null    object
dtypes: int64(2), object(3)
memory usage: 4.0+ KB

In [8]:
df.isnull().sum()

NombreMunicipio            4
CodigoMunicipio            0
Ubicación                  6
NombreRegion               0
CodigoRegion               0
Anio                       4
CausaMortalidad            0
TipoPoblacionObjetivo      0
NumeroPoblacionObjetivo    5
NumeroCasos                9
dtype: int64

In [10]:
#REMPLAZAR NULOS DE LA COLUMNA "NumeroPoblacionObjetivo" con la media
df["NumeroPoblacionObjetivo"] = df["NumeroPoblacionObjetivo"].fillna(df["NumeroPoblacionObjetivo"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          96 non-null     object
 1   CodigoMunicipio          100 non-null    int64
 2   Ubicación                94 non-null     object
 3   NombreRegion             100 non-null    object
 4   CodigoRegion             100 non-null    int64
 5   Anio                     96 non-null     float64
 6   CausaMortalidad          100 non-null    object
 7   TipoPoblacionObjetivo    100 non-null    object
 8   NumeroPoblacionObjetivo  100 non-null    float64
 9   NumeroCasos              91 non-null     float64
dtypes: float64(3), int64(2), object(5)
memory usage: 7.9+ KB

In [11]:
df.head(20)

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2.358330e+06,71.0
1,Amalfi,5376,POINT (-75.3433 6.6311),NORDESTE,4,NaN,Suicidios,Poblacion total,1.254396e+06,37.0
2,Medellín,5343,NaN,VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,1.502942e+06,NaN
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1.467689e+06,52.0
4,NaN,5921,POINT (-75.2021 6.4843),OCCIDENTE,6,2012.0,Suicidios,Poblacion total,2.057555e+06,1.0
5,Bello,5848,POINT (-75.8892 6.7863),VALLE DE ABURRA,1,2018.0,Suicidios,Poblacion total,1.404107e+06,39.0
6,Caldas,5443,POINT (-75.9006 6.3568),VALLE DE ABURRA,1,NaN,Suicidios,Poblacion total,9.807320e+05,64.0
7,Alejandría,5127,POINT (-75.4561 6.7184),ORIENTE,7,2005.0,Suicidios,Poblacion total,1.254396e+06,4.0
8,Bello,5838,POINT (-75.9154 6.6056),VALLE DE ABURRA,1,2009.0,Suicidios,Poblacion total,4.915700e+05,103.0
9,NaN,5790,POINT (-75.8035 6.2484),URABA,9,2013.0,Suicidios,Poblacion total,2.318121e+06,41.0
10,Apartadó,5135,POINT (-75.4242 6.5636),URABA,9,2011.0,Suicidios,Poblacion total,9.755480e+05,142.0
11,Caldas,5739,POINT (-75.4627 6.6450),VALLE DE ABURRA,1,2010.0,Suicidios,Poblacion total,2.063083e+06,27.0
12,Caldas,5555,POINT (-75.8526 6.9901),VALLE DE ABURRA,1,2017.0,Suicidios,Poblacion total,1.629880e+06,2.0
13,Andes,5663,POINT (-75.2853 6.7585),SUROESTE,8,2013.0,Suicidios,Poblacion total,2.217603e+06,112.0
14,Abejorral,5783,POINT (-75.6249 6.6172),ORIENTE,7,2006.0,Suicidios,Poblacion total,1.402804e+06,128.0
15,Abejorral,5610,POINT (-75.8777 6.1197),ORIENTE,7,2010.0,Suicidios,Poblacion total,2.467604e+06,NaN
16,Amagá,5919,POINT (-75.3911 6.2734),SUROESTE,8,2008.0,Suicidios,Poblacion total,9.126810e+05,146.0
17,Caldas,5445,POINT (-75.1262 6.7287),VALLE DE ABURRA,1,2022.0,Suicidios,Poblacion total,1.858926e+06,41.0
18,Amalfi,5758,POINT (-75.8400 6.4170),NORDESTE,4,2009.0,Suicidios,Poblacion total,1.243082e+06,8.0
19,Abejorral,5572,NaN,ORIENTE,7,2012.0,Suicidios,Poblacion total,7.939710e+05,103.0

In [12]:
# Cambuar los nulos de la columna Numero de Casos con la mediana
df["NumeroCasos"] = df["NumeroCasos"].fillna(df["NumeroCasos"].median())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          96 non-null     object
 1   CodigoMunicipio          100 non-null    int64
 2   Ubicación                94 non-null     object
 3   NombreRegion             100 non-null    object
 4   CodigoRegion             100 non-null    int64
 5   Anio                     96 non-null     float64
 6   CausaMortalidad          100 non-null    object
 7   TipoPoblacionObjetivo    100 non-null    object
 8   NumeroPoblacionObjetivo  100 non-null    float64
 9   NumeroCasos              100 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 7.9+ KB

In [13]:
df

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2.358330e+06,71.0
1,Amalfi,5376,POINT (-75.3433 6.6311),NORDESTE,4,NaN,Suicidios,Poblacion total,1.254396e+06,37.0
2,Medellín,5343,NaN,VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,1.502942e+06,57.0
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1.467689e+06,52.0
4,NaN,5921,POINT (-75.2021 6.4843),OCCIDENTE,6,2012.0,Suicidios,Poblacion total,2.057555e+06,1.0
...,...,...,...,...,...,...,...,...,...,...
95,Medellín,5500,POINT (-75.5873 6.5806),VALLE DE ABURRA,1,2013.0,Suicidios,Poblacion total,1.254396e+06,31.0
96,Caldas,5322,POINT (-75.2500 6.7737),VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,2.066150e+05,57.0
97,Bello,5282,POINT (-75.1130 6.3983),VALLE DE ABURRA,1,2007.0,Suicidios,Poblacion total,5.617230e+05,44.0
98,Abriaquí,5269,NaN,OCCIDENTE,6,2005.0,Suicidios,Poblacion total,1.013727e+06,107.0
99,Apartadó,5847,POINT (-75.3032 6.9436),URABA,9,2018.0,Suicidios,Poblacion total,5.426590e+05,28.0

In [15]:
# remplazar los datos nulos de la columna año con la moda
df["Anio"] = df["Anio"].fillna(df["Anio"].mode()[0])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          96 non-null     object
 1   CodigoMunicipio          100 non-null    int64
 2   Ubicación                94 non-null     object
 3   NombreRegion             100 non-null    object
 4   CodigoRegion             100 non-null    int64
 5   Anio                     100 non-null    float64
 6   CausaMortalidad          100 non-null    object
 7   TipoPoblacionObjetivo    100 non-null    object
 8   NumeroPoblacionObjetivo  100 non-null    float64
 9   NumeroCasos              100 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 7.9+ KB

In [16]:
df

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2.358330e+06,71.0
1,Amalfi,5376,POINT (-75.3433 6.6311),NORDESTE,4,2009.0,Suicidios,Poblacion total,1.254396e+06,37.0
2,Medellín,5343,NaN,VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,1.502942e+06,57.0
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1.467689e+06,52.0
4,NaN,5921,POINT (-75.2021 6.4843),OCCIDENTE,6,2012.0,Suicidios,Poblacion total,2.057555e+06,1.0
...,...,...,...,...,...,...,...,...,...,...
95,Medellín,5500,POINT (-75.5873 6.5806),VALLE DE ABURRA,1,2013.0,Suicidios,Poblacion total,1.254396e+06,31.0
96,Caldas,5322,POINT (-75.2500 6.7737),VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,2.066150e+05,57.0
97,Bello,5282,POINT (-75.1130 6.3983),VALLE DE ABURRA,1,2007.0,Suicidios,Poblacion total,5.617230e+05,44.0
98,Abriaquí,5269,NaN,OCCIDENTE,6,2005.0,Suicidios,Poblacion total,1.013727e+06,107.0
99,Apartadó,5847,POINT (-75.3032 6.9436),URABA,9,2018.0,Suicidios,Poblacion total,5.426590e+05,28.0

In [17]:
# Remplazar nulos de la columna Nombremunicipio con un valor fijo
df["NombreMunicipio"] = df["NombreMunicipio"].fillna("Desconocido")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          100 non-null    object
 1   CodigoMunicipio          100 non-null    int64
 2   Ubicación                94 non-null     object
 3   NombreRegion             100 non-null    object
 4   CodigoRegion             100 non-null    int64
 5   Anio                     100 non-null    float64
 6   CausaMortalidad          100 non-null    object
 7   TipoPoblacionObjetivo    100 non-null    object
 8   NumeroPoblacionObjetivo  100 non-null    float64
 9   NumeroCasos              100 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 7.9+ KB

In [18]:
df

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2.358330e+06,71.0
1,Amalfi,5376,POINT (-75.3433 6.6311),NORDESTE,4,2009.0,Suicidios,Poblacion total,1.254396e+06,37.0
2,Medellín,5343,NaN,VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,1.502942e+06,57.0
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1.467689e+06,52.0
4,Desconocido,5921,POINT (-75.2021 6.4843),OCCIDENTE,6,2012.0,Suicidios,Poblacion total,2.057555e+06,1.0
...,...,...,...,...,...,...,...,...,...,...
95,Medellín,5500,POINT (-75.5873 6.5806),VALLE DE ABURRA,1,2013.0,Suicidios,Poblacion total,1.254396e+06,31.0
96,Caldas,5322,POINT (-75.2500 6.7737),VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,2.066150e+05,57.0
97,Bello,5282,POINT (-75.1130 6.3983),VALLE DE ABURRA,1,2007.0,Suicidios,Poblacion total,5.617230e+05,44.0
98,Abriaquí,5269,NaN,OCCIDENTE,6,2005.0,Suicidios,Poblacion total,1.013727e+06,107.0
99,Apartadó,5847,POINT (-75.3032 6.9436),URABA,9,2018.0,Suicidios,Poblacion total,5.426590e+05,28.0

In [24]:
# Remplazar los valores nulos de la columna Ubicación con un valor fijo
df["Ubicación"] = df["Ubicación"].fillna("No Aplica")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          100 non-null    object
 1   CodigoMunicipio          100 non-null    int64
 2   Ubicación                100 non-null    object
 3   NombreRegion             100 non-null    object
 4   CodigoRegion             100 non-null    int64
 5   Anio                     100 non-null    float64
 6   CausaMortalidad          100 non-null    object
 7   TipoPoblacionObjetivo    100 non-null    object
 8   NumeroPoblacionObjetivo  100 non-null    float64
 9   NumeroCasos              100 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 7.9+ KB

In [25]:
df

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Apartadó,5566,POINT (-75.6734 6.7265),URABA,9,2019.0,Suicidios,Poblacion total,2.358330e+06,71.0
1,Amalfi,5376,POINT (-75.3433 6.6311),NORDESTE,4,2009.0,Suicidios,Poblacion total,1.254396e+06,37.0
2,Medellín,5343,Desconocido,VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,1.502942e+06,57.0
3,Amagá,5466,POINT (-75.8041 6.7235),SUROESTE,8,2018.0,Suicidios,Poblacion total,1.467689e+06,52.0
4,Desconocido,5921,POINT (-75.2021 6.4843),OCCIDENTE,6,2012.0,Suicidios,Poblacion total,2.057555e+06,1.0
...,...,...,...,...,...,...,...,...,...,...
95,Medellín,5500,POINT (-75.5873 6.5806),VALLE DE ABURRA,1,2013.0,Suicidios,Poblacion total,1.254396e+06,31.0
96,Caldas,5322,POINT (-75.2500 6.7737),VALLE DE ABURRA,1,2020.0,Suicidios,Poblacion total,2.066150e+05,57.0
97,Bello,5282,POINT (-75.1130 6.3983),VALLE DE ABURRA,1,2007.0,Suicidios,Poblacion total,5.617230e+05,44.0
98,Abriaquí,5269,Desconocido,OCCIDENTE,6,2005.0,Suicidios,Poblacion total,1.013727e+06,107.0
99,Apartadó,5847,POINT (-75.3032 6.9436),URABA,9,2018.0,Suicidios,Poblacion total,5.426590e+05,28.0

##EJERCICIO LIMPIEZA DE DATOS

In [27]:
import numpy as np

In [28]:
# Creación del diccionario con datos
datos_energia = {
    "Ciudad": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Bogotá", "Cali", "Medellín", np.nan],
    "Consumo_kWh": [350, 420, np.nan, 390, 310, 405, np.nan, 450],
    "Estrato": [3, 4, 3, np.nan, 2, 3, 4, 2],
    "Subsidio": [True, False, True, True, np.nan, True, False, True]
}

# Creación del DataFrame
df = pd.DataFrame(datos_energia)

In [29]:
df

         Ciudad  Consumo_kWh  Estrato Subsidio
0        Bogotá        350.0      3.0     True
1      Medellín        420.0      4.0    False
2          Cali          NaN      3.0     True
3  Barranquilla        390.0      NaN     True
4        Bogotá        310.0      2.0      NaN
5          Cali        405.0      3.0     True
6      Medellín          NaN      4.0    False
7           NaN        450.0      2.0     True

In [36]:
#Paso 1: Detección y conteo
#Instrucción: Usa .isnull() y .sum() para contar nulos por columna.
#Pregunta a responder: ¿Cuántos valores faltantes hay en total?

total_nulos= df.isnull().sum()
total_nulos

Ciudad         1
Consumo_kWh    2
Estrato        1
Subsidio       1
dtype: int64

In [34]:
total_nulos.sum()
#Existen 5 valores nulos en total

np.int64(5)

In [37]:
#Paso 2: Eliminación
#Instrucción: Crea una copia del DataFrame y elimina:
#Las filas que tengan al menos un NaN.
#Las columnas que tengan al menos un NaN.
#Pregunta a responder: ¿Cuánta información se pierde en cada caso?

df_sin_filas_nulas = df.dropna()
df_sin_filas_nulas

#Se pierden 5 filas

     Ciudad  Consumo_kWh  Estrato Subsidio
0    Bogotá        350.0      3.0     True
1  Medellín        420.0      4.0    False
5      Cali        405.0      3.0     True

In [39]:
#Eliminación de columnas con datos nulos
df_sin_columnas_nulas = df.dropna(axis=1)
df_sin_columnas_nulas

#Se pierden todas las columnas

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7]

In [40]:
#Paso 3: Imputación
#Instrucción: Imputa los valores faltantes de estas formas:
#Consumo_kWh: reemplazar con la media.
df["Consumo_kWh"] = df["Consumo_kWh"].fillna(df["Consumo_kWh"].mean())
df

         Ciudad  Consumo_kWh  Estrato Subsidio
0        Bogotá        350.0      3.0     True
1      Medellín        420.0      4.0    False
2          Cali        387.5      3.0     True
3  Barranquilla        390.0      NaN     True
4        Bogotá        310.0      2.0      NaN
5          Cali        405.0      3.0     True
6      Medellín        387.5      4.0    False
7           NaN        450.0      2.0     True

In [41]:
#Paso 3: Imputación
#Estrato: reemplazar con la mediana.
df["Estrato"] = df["Estrato"].fillna(df["Estrato"].median())
df

         Ciudad  Consumo_kWh  Estrato Subsidio
0        Bogotá        350.0      3.0     True
1      Medellín        420.0      4.0    False
2          Cali        387.5      3.0     True
3  Barranquilla        390.0      3.0     True
4        Bogotá        310.0      2.0      NaN
5          Cali        405.0      3.0     True
6      Medellín        387.5      4.0    False
7           NaN        450.0      2.0     True

In [42]:
#Ciudad: reemplazar con la moda.
df["Ciudad"] = df["Ciudad"].fillna(df["Ciudad"].mode()[0])
df

         Ciudad  Consumo_kWh  Estrato Subsidio
0        Bogotá        350.0      3.0     True
1      Medellín        420.0      4.0    False
2          Cali        387.5      3.0     True
3  Barranquilla        390.0      3.0     True
4        Bogotá        310.0      2.0      NaN
5          Cali        405.0      3.0     True
6      Medellín        387.5      4.0    False
7        Bogotá        450.0      2.0     True

In [43]:
#Subsidio: reemplazar con un valor fijo (False).
df["Subsidio"] = df["Subsidio"].fillna(False)
df

/tmp/ipykernel_1499/1378255955.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Subsidio"] = df["Subsidio"].fillna(False)

         Ciudad  Consumo_kWh  Estrato  Subsidio
0        Bogotá        350.0      3.0      True
1      Medellín        420.0      4.0     False
2          Cali        387.5      3.0      True
3  Barranquilla        390.0      3.0      True
4        Bogotá        310.0      2.0     False
5          Cali        405.0      3.0      True
6      Medellín        387.5      4.0     False
7        Bogotá        450.0      2.0      True