<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas es una libreria especializada en el analisis,manipulación y limpieza de datos estructurados, como los que se vienen en archivos .csv,Excel,bases de datos,etc.
# Es la herramienta mas usada para el análisis de datos.
#Facilita tareas que antes eran tediosas: limpieza,filtrado,ordenamiento,agrupación,calculo de promedios,conteos,etc.

# ¿Que podemos hacer con Pandas?
# Leer archivos y transformarlos en tablas.
# Explorar datos ( ver las primeras fils,tipos,valores faltantes)
# Filtrar y seleccionar columnas o filas.
#Ordenas,agrupar y resumir información.
#Limpiar datos (quitar duplicados,tratar nulos,cambiar formatos)
#Crear columnas nuevas,combinar tablas,aplicas funciones.

In [2]:
import pandas as pd

In [ ]:
#Una series es una estructura de datos unidimensional de Pandas, similar a una lista o un arreglo de Numpy, pero con etiquetas (indices) para cada elemento.
#Es ideal para representar una columna de datos, edad, estatura. etc.

In [4]:
edades = pd.Series([25,30,28,22,35])
print(edades)

0    25
1    30
2    28
3    22
4    35
dtype: int64

In [10]:

# Indices en  Series de Pandas
edades = pd.Series([25,30,28,22,35], index=["Starleen", "Liza","Steven", "Amparito", "Maria F"])
print(edades)

Starleen    25
Liza        30
Steven      28
Amparito    22
Maria F     35
dtype: int64

In [13]:
print(edades["Steven"])
#

28

In [14]:
print(edades[2])
#

28

/tmp/ipykernel_6697/2051348959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(edades[2])

In [15]:
print(edades[0:3])
#

Starleen    25
Liza        30
Steven      28
dtype: int64

In [19]:
print(edades[3])

22

/tmp/ipykernel_6697/870832776.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(edades[3])

## QUE ES UN DATA FRAME

In [22]:
# Es una estructura que parece una tabla de datos que contiene filas e indices, y columnas con nombre, es la estructura principal de trabajo en pandas

#Crear un dataframe desde un diccionario.

# Explicación: Cada  clave del diccionario es una columna.
#Cada valor (lista) representa los datos de esa  columna
# El dataframe organiza todo en una tabla ordenada.

In [23]:
# Crear un diccionario
datos = {
    # Clave  = Valor
    "Nombre": ["Starleen", "Liza","Steven", "Amparito", "Maria F"],
    "Edad": [25,30,28,22,35],
    "Ciudad": ["Medellin", "Bogota", "Bucaramanda", "Bogota", "Cali"]
}

In [25]:
df= pd.DataFrame(datos)  # Convierte el diccionario en un dataframe
print(df)

     Nombre  Edad       Ciudad
0  Starleen    25     Medellin
1      Liza    30       Bogota
2    Steven    28  Bucaramanda
3  Amparito    22       Bogota
4   Maria F    35         Cali

In [26]:
print(datos)

{'Nombre': ['Starleen', 'Liza', 'Steven', 'Amparito', 'Maria F'], 'Edad': [25, 30, 28, 22, 35], 'Ciudad': ['Medellin', 'Bogota', 'Bucaramanda', 'Bogota', 'Cali']}

In [32]:
# Ver las primeras y últimas filas del dataframe
print(df.head(2)) # muestra las primeras filas

     Nombre  Edad    Ciudad
0  Starleen    25  Medellin
1      Liza    30    Bogota

In [37]:
# Mostrar las últimas filas del dataframe
print(df.tail(3))

     Nombre  Edad       Ciudad
2    Steven    28  Bucaramanda
3  Amparito    22       Bogota
4   Maria F    35         Cali

In [41]:

# Ver dimensiones y estructura básica
print("Filas y columnas:" , df.shape)
print("Numero de filas:" , len(df))
print("Tipo de datos:",df.dtypes)

Filas y columnas: (5, 3)
Numero de filas: 5
Tipo de datos: Nombre    object
Edad       int64
Ciudad    object
dtype: object

In [43]:
# resumen general del Dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  5 non-null      object
 1   Edad    5 non-null      int64
 2   Ciudad  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [44]:
# Resumen estadistico del dataframe, SOLO de columnas númericas.
df.describe()

            Edad
count   5.000000
mean   28.000000
std     4.949747
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    35.000000

In [46]:
# Modificación de COlumnas en el Dataset
# Renombrar columnas es útil para estandarizar o traducir encabezados antes decompartir o exportar.
df.rename(columns={"Nombre":"Nombre completo"}, inplace=True)
#print(df)
df

  Nombre completo  Edad       Ciudad
0        Starleen    25     Medellin
1            Liza    30       Bogota
2          Steven    28  Bucaramanda
3        Amparito    22       Bogota
4         Maria F    35         Cali

In [47]:
# Agregar una nueva columna al dataframe
# Puedes crear columnas nuevas desde listas (misma longitud que el Dataframe).
# esto es clave cuando agregas resultados

df["Estrato"] = [3,4,2,6,6]
df

  Nombre completo  Edad       Ciudad  Estrato
0        Starleen    25     Medellin        3
1            Liza    30       Bogota        4
2          Steven    28  Bucaramanda        2
3        Amparito    22       Bogota        6
4         Maria F    35         Cali        6

## ACTIVIDAD CON DATAFRAME

In [49]:
# Crear el diccionario

estudiantes = {
    "Nombre": ["Starleen", "Liza","Steven", "Amparito", "Maria F"],
    "Edad": [25,30,28,22,35],
    "Programa": ["Ingenieria","Psicología","Medicina","Derecho","Contabilidad"]
}

# Convertirlo en Dataframe

df_estudiantes = pd.DataFrame(estudiantes)
df_estudiantes

     Nombre  Edad      Programa
0  Starleen    25    Ingenieria
1      Liza    30    Psicología
2    Steven    28      Medicina
3  Amparito    22       Derecho
4   Maria F    35  Contabilidad

In [50]:
# Ver las primeras 3 filas
df_estudiantes.head(3)

     Nombre  Edad    Programa
0  Starleen    25  Ingenieria
1      Liza    30  Psicología
2    Steven    28    Medicina

In [51]:
# Ver las últimas 2 filas
df_estudiantes.tail(2)

     Nombre  Edad      Programa
3  Amparito    22       Derecho
4   Maria F    35  Contabilidad

In [52]:
df_estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    5 non-null      object
 1   Edad      5 non-null      int64
 2   Programa  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [53]:
df_estudiantes.describe()

            Edad
count   5.000000
mean   28.000000
std     4.949747
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    35.000000

In [55]:
# Agregar una nueva columna al data frame
df_estudiantes["Nota_Final"]= [4,4.2,4.3,3.5,3]
df_estudiantes

     Nombre  Edad      Programa  Nota_Final
0  Starleen    25    Ingenieria         4.0
1      Liza    30    Psicología         4.2
2    Steven    28      Medicina         4.3
3  Amparito    22       Derecho         3.5
4   Maria F    35  Contabilidad         3.0

In [56]:
df_estudiantes.rename(columns={"Nota_Final":"Promedio"}, inplace=True)
df_estudiantes

     Nombre  Edad      Programa  Promedio
0  Starleen    25    Ingenieria       4.0
1      Liza    30    Psicología       4.2
2    Steven    28      Medicina       4.3
3  Amparito    22       Derecho       3.5
4   Maria F    35  Contabilidad       3.0