<a href="https://colab.research.google.com/github/Starleen1996/analisis_datos_curso/blob/main/pandas_documentos_clase6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# cargar archivos, importar directamente a colab, crear el botón para adjuntar archivos
from google.colab import files
files.upload()

Saving DASBOARD PROFESIONAL.xlsx to DASBOARD PROFESIONAL.xlsx
Saving Superservicios-Información_de_Accidentes_de_Origen_Eléctrico-Formato19_20260929.csv to Superservicios-Información_de_Accidentes_de_Origen_Eléctrico-Formato19_20260929.csv

{'DASBOARD PROFESIONAL.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00b\xee\x9dh^\x01\x00\x00\x90\x04\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x94\xcbN\xc30\x10E\xf7H\xfcC\xe4-J\xdc\xb2@\x085\xed\x82\xc7\x12*Q>\xc0\xc4\x93\xc6\xaac[\x9eii\xff\x9e\x89\xfb\x10B\xa1\x15j7\xb1\x12\xcf\xdc{2\xf1\xcdh\xb2nm\xb6\x82\x88\xc6\xbbR\x0c\x8b\x81\xc8\xc0U^\x1b7/\xc5\xc7\xec%\xbf\x17\x19\x92rZY\xef\xa0\x14\x1b@1\x19__\x8df\x9b\x00\x98q\xb7\xc3R4D\xe1AJ\xac\x1ah\x15\x16>\x80\xe3\x9d\xda\xc7V\x11\xdf\xc6\xb9\x0c\xaaZ\xa89\xc8\xdb\xc1\xe0NV\xde\x118\xca\xa9\xd3\x10\xe3\xd1\x13\xd4ji){^\xf3\xe3-I\x04\x8b"{\xdc\x16v^\xa5P!XS)bR\xb9r\xfa\x97K\xbes(\xb83\xd5`c\x02\xde0\x86\x90\xbd\x0e\xdd\xce\xdf\x06\xbb\xbe7\x1eM4\x1a\xb2\xa9\x8a\xf4\xaaZ\xc6\x90k+\xbf|\\|z\xbf(\x8e\x8b\xf4P\xfa\xba6\x15h_-[\x9e@\x81!\x82\xd2\xd8\x00Pk\x8b\xb4\x16\xad2n\xcf}\xc4?\x15\xa3L\xcb\xf0\xc2 \xdd\xfb%\xe1\x13\x1c\xc4\xdf\x1bd\xba\x9e\x8f\x90dN\x18"m,\xe0\xa5\xc7\x9eDO97*\x82~\xa7\xc8\xc9\xb88\xc0O\xedc\x1c|n\xa6\xd1\x07\xe4\x04E\xf8\xff\x14\xf6\x11\xe9\xba\xf3\xc0B\x10\xc9\xc0!$}\x87\xed\xe0\xc8\xe9;{\xec\xd0\xe5[\x83\xee\xf1\x96\xe9\x7f2\xfe\x06\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xb5U0#\xf4\x00\x00\x00L\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92MO\xc30\x0c\x86\xefH\xfc\x87\xc8\xf7\xd5\xdd\x90\x10BKwAH\xbb!T~\x80I\xdc\x0f\xb5\x8d\xa3$\x1b\xdd\xbf\'\x1c\x10T\x1a\x83\x03G\x7f\xbd~\xfc\xca\xdb\xdd<\x8d\xea\xc8!\xf6\xe24\xac\x8b\x12\x14;#\xb6w\xad\x86\x97\xfaqu\x07*&r\x96Fq\xac\xe1\xc4\x11v\xd5\xf5\xd5\xf6\x99GJy(v\xbd\x8f*\xab\xb8\xa8\xa1K\xc9\xdf#F\xd3\xf1D\xb1\x10\xcf.W\x1a\t\x13\xa5\x1c\x86\x16=\x99\x81Z\xc6MY\xdeb\xf8\xae\x01\xd5BS\xed\xad\x86\xb0\xb77\xa0\xea\x93\xcf\x9b\x7f\xd7\x96\xa6\xe9\r?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x81>\x94\x97\xf3\x00\x00\x00\xba\x02\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xacRMK\xc40\x10\xbd\x0b\xfe\x870w\x9bv\x15\x11\xd9t/"\xecU\xeb\x0f\x08\xc9\xb4)\xdb&!3~\xf4\xdf\x1b*\xba]X\xd6K/\x03o\x86y\xef\xcd\xc7v\xf75\x0e\xe2\x03\x13\xf5\xc1+\xa8\x8a\x12\x04z\x13l\xef;\x05o\xcd\xf3\xcd\x03\x08b\xed\xad\x1e\x82G\x05\x13\x12\xec\xea\xeb\xab\xed\x0b\x0e\x9as\x13\xb9>\x92\xc8,\x9e\x148\xe6\xf8(%\x19\x87\xa3\xa6"D\xf4\xb9\xd2\x864j\xce0u2js\xd0\x1d\xcaMY\xde\xcb\xb4\xe4\x80\xfa\x84S\xec\xad\x82\xb4\xb7\xb7 \x9a)f\xe5\xff\xb9C\xdb\xf6\x06\x9f\x82y\x1f\xd1\xf3\x19\tI<\ry\x00\xd1\xe8\xd4!+\xf8\xc1E\xf6\x08\xf2\xbc\xfcfMy\xcek\xc1\xa3\xfa\x0c\xe5\x1c\xabK\x1e\xaa5=|\x86t \x87\xc8G\x1f\x7f)\x92s\xe5\xa2\x99\xbbU\xef\xe1tB\xfb\xca)\xbf\xdb\xf2,\xcb\xf4\xeff\xe4\xc9\xc7\xd5\xdf\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xac\xf1\xde\r6\x02\x00\x00\x92\x04\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xacT\xcb\x8e\xd30\x14\xdd#\xf1\x0f\x96\xf7i\x1eM;m\xd4d\xd4\x17\xa2\x12B\xa3\xa13\xb3\xe9\xc6u\x9c\xc6\xaa\x1f\xc1vh+\xc4\xbfs\x93\x10(t3\x086\xf1\xb5c\x1f\xdfs\xce\xbd\x9e\xdd\x9f\xa5@_\x98\xb1\\\xab\x14\x87\x83\x00#\xa6\xa8\xce\xb9:\xa4\xf8i\xfb\xce\x9b`d\x1dQ9\x11Z\xb1\x14_\x98\xc5\xf7\xd9\xdb7\xb3\x936\xc7\xbd\xd6G\x04\x00\xca\xa6\xb8t\xaeJ|\xdf\xd2\x92Ib\x07\xbab\n\xfe\x14\xdaH\xe2`j\x0e\xbe\xad\x0c#\xb9-\x19sR\xf8Q\x10\x8c}I\xb8\xc2\x1dBb^\x83\xa1\x8b\x82S\xb6\xd2\xb4\x96L\xb9\x0e\xc40A\x1c\xa4oK^\xd9\x1eM\xd2\xd7\xc0Ib\x8eu\xe5Q-+\x80\xd8s\xc1\xdd\xa5\x05\xc5H\xd2dsP\xda\x90\xbd\x00\xda\xe7p\xd4#Cx\x03-95\xda\xea\xc2\r\x00\xca\xef\x92\xbc\xe1\x1b\x06~\x18v\x94\xb3Y\xc1\x05{\xeedG\xa4\xaa>\x12\xd9\xdc"0\x12\xc4\xbau\xce\x1d\xcbS<\x86\xa9>\xb1\xdf\x16L]-j.\xe0o\x18\xc7Q\x80\xfd\xec\xa7\x15\x0f\x06\xe5\xac \xb5p[0\xa1\x87\x87\x8d\xe38\x08\xc3f\'\x90\x9a\x0b\xc7\x8c"\x8e-\xb5r\xa0\xe1\x0f\xf5\xffU\xaf\x16{Yjp\x07=\xb2\xcf57\x0c\x8a\xa2\x91-\x9b\xc1\x97\xd0\x84\xec\xed\x03q%\xaa\x8dH\xf12\xd9=Y\xa0\xbf\xfbTK\xae\xb8u \x1f\x9a\xe7\xe0\xe4\xae7\xd7\xee\xae\x14\'\xb7v\xfe\x85\xe6\x846\xe4}`\xdfe\xd8\xc5\x7f*\x91\xcd\x9az~\xe6\xecd\x7fi\xdaL\xd1\xf9\x85\xab\\\x9fR\x0c\xddq\xb9\x8aO\xed\xf2\x0b\xcf]\t*\x0f\xc3\t\x14I\xb7\xf6\x9e\xf1C\xe9R\x1c\x87qk\x91\x7f\x05\xddv\x00\\\xd1\x8eH\xb5\xce\xaf\xe6\xdb94Z\xd3\x1b\x9b\xc6Z\x8cL\xc2!0\x9b\xbc5\xce\xef\x0fQ"(\xf8\xdc\x0c\xed\xc6q4\r\x87\r;vv\x1f\xackG\x90\x98\xa7\xf8+\\=\xbf\x0b\xa6\xb1\x17\xac\x87#/\x9eL#o\x12\x0f#o\x19\xaf\xa2\xf5\xe8n\xbdZ/F\xdf\xfeoU\x83\xd3I\xff04Y\x96\xc4\xb8\xad!\xf4\x08\xcf\xc9#+\x16\xc4B\x95w\x84 _\xb0\xa1\xcf\xda\xefOe\xdf\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00`i\x8a\xe3\xe4\r\x00\x00\xef.\x00\x00\x14\x00\x00\x00xl/sharedStrings.xml|Z\xdbr\x1b7\x12}\xdf\xaa\xfd\x07\x94\xde\x19%\xaedwk\xcbv\x8a\x17K2E\xca\\R\x91\xca\x8f\xe0\x0c4\x83\x08\x030\x00\x86\xf2\xe8o\xf6\x03\xf2\x94?X\xff\xd8\x1e`(\xdb\x99\xee\xc9K.\x1c\xcd\x00ht\x9fs\xfa\x00\xaf\x7f\xfe\xd4\x18qT>hg\xdf\x9c\xfd\xf0\xdd\xf7gB\xd9\xc2\x95\xdaVo\xce~\xb9\xbd\x98\xfc\xebL\x84(m)\x8d\xb3\xea\xcdY\xa7\xc2\xd9\xcfo\xff\xfe\xb7\xd7!D\x81wmxsV\xc7x\xf8\xf7\xf9y(j\xd5\xc8\xf0\x9d;(\x8b\'\x0f\xce72\xe2\x7f}u\x1e\x0e^\xc92\xd4J\xc5\xc6\x9c\xbf\xfa\xfe\xfb\x7f\x9c7R\xdb3Q\xb8\xd6F\x8c\xfb\xd3\x0f\xaf\xceDk\xf5o\xad\x9a\xf7?\xfd\xf8\xea_go_\x07\xfd\xf6u|{\xa1\x8aZ\x8aR\x19\x11\x94?\xeaB\xbb\xd7\xe7\xf1\xed\xeb\xf3\xf4\xb4\xff\x8b\x1b\xd7\xec\xbd\x12\x85\xd1\xcaF5|:\xb5\xba\x91f\xf8\xebV>K\x81\t\x17.\xca\x91\xef\x1dd\xc1~\xf0]\x88\xcak\xa3\x9fe\xe9~\x1e\xbe\xbb;\xcdQxU\xe8\xbd.\xc9d\xd7\xceF\'\x0e\xb2\xc2\xdb\xc3\x97\xd7\xaa\xd4\x85\x13w*\r`\xa5\xd7N &BFeK\xfd\xf9\x8f\xe1\x9f/\xb4\xac\xec\xe7?B\xc4K\xc3g\xb7^F\xd9\xa4\xf9\x93G[Ua\xbf\xc9\xc4ki\xad\xb3b\x8e\x1d4\xd8\xf2\xe1\xf3\x8d\xf2\x9e|j\xe3\x9eJ\xe5g\xa6\xa5Q7]\x08$\xb2\xbb\xcf\xbf\xff\xef\xf7\xe1\x97\xbf\xc6\xb3\xc0"\xc9\xc4\x16\xfe;\xb1\xd3M\xe3l\x18\xbe\xf9\xde>\xa8"\xbf$\xda>`d\xc4\xad\xaa\xe5\x1e\x9b\x15\xb1\x99\xcc\xc7o\xd4\x93\xf8\xe8\xfc\xe3\xf0\xcb+\xd9z)v\xc8\x8e8|t_+I~\x9c6\x1dYV\xa3|\x85r\xd2dNiEsg\x8d"\xef\\\xca\x10\xbdKY\xecu\xd4d\xbdS\x1b\x91S\x9f\xffH\x1bN\x1e\xae\xa5\xef\xb8\x8dK\xa3]\xebf\xaf\xbc\xe9\xc4J\xfa@\xf7\xfeR\xd2,\xb9t\xa6Tv\xebH"\xcck\xafCt\x87Zy\x92\x90*\xd86z\xd4(\x13\xea\xb9\xf6m\xf5\xf9wT\x9d\xb2\x8e\xbc\x8axXU`a-\x89\xedB\x1eu).\x8c\x8a\xc0\x18\xf2\xe2\xf4Hs\xaf\x8d\x0e\xe8\xa3JQ\xbb\xc6a\x0f\x94k\x83\x08mQ\xa8@\xc2\x86\x82E9P\x08\x18\xfer\'\x8b\xd6\xf2I\x94"\xbc\xc1\xaa\xc9D>Dn\x177\xca\xda\xd0\x99\xa3\xb445vQ\x1d\x95\x15\x97\xce>K\xa3\x9eIZ\xea\xaa\x8e\x1f\x951\xeei\xf8h\xe6uY)\x12\xbc;d~\x03,!\xeb\x9ey\x149\xea}\xdd\x01\xffI\xb1\xb7\xfe`\xc8r\x16\xd8#\x92\xcc\xd88\xa4\xac\x01@\x8b\x83\n$\x90)6\xeb\xd6\x18M\xab\xf7\x0e\xa8&\x7f%\xa3lk\x87o\xbd\x0f\\./\x01B\x9dX\xba\xda2Y\x8c\x99\xa8_\xc9\x04\xa6\xcf\xad\'c\\9cH\xf1]xYD\x94=\xd9y\xe5\x01>$\xb2}\x1dh\xabD\x82F\xf2\xb5\x0f \xc2\x89\xf4E\xad#\xf2\x1a\xb9X\xb8\xe6\xe0\x02\xfeO$\x8e\x14\xa1\x03\x8d4\xc3\xb1\xa6F}\xa2u\xbf\xd3\x18A\x8a\xb56\x86\x16\xc0*\xe5\x04\xf2F\x19\x0e\x87?\x1eSa\x91\xf4\x06\xec!\x96\x81"P\x0f|\xd7\xba$u\x7f\xf5\xf9\xbfMb\xbe\xe1\xb7nS\xadQf\x90\x19\x07(\x03$H\x15\xbbF\xc7z\xf8\xa1\x0f\xa6\\IZDK\x94\x8b~\xa0\xe3\xae%\x08\xa6\xa8\xdb\xa0b\xa4`\xa8\x81\x15\x88\x96\xd8\xe2?\xa4/\x99t\xd9\xc8\x83\xec\xe4}\xad\x0f\x04\xc6\x90\xb3W\xd2\x1f\x99\xe8\xe8 \xc5%v\x95V.\xb2\xefAWH\x9f=F\xf5\x99b\xa5\x11\x8f\xd6=\x19\x85\xc2\xdc\xcb@\xeb\tD\xfb$ivNQ.\x98\xb0\xd8=j\xec\x1d\t\xf8\x06\xc80\x8a\xce\x89\x05\x86\xeb\xc1\xd4Bk\xa2\x14\t\n=\xd5BS\xab\x1a\x06\x8a\x80\x0f\x9d\x98\xcb\xe6\xb0G$\x87\xdf\xdci\x03\xe18\xfcuI\xf2 \xd5*\n\x04y\x13\x14\xa1\xf6wID\xed\x15M\x85D\xcbW\x189\xd4\x9a\x86g\xe6\x9d{T\x02Q\xa2_L\n\xaam6,|]\'\xde\x02\x14\x92\xf0\xc8f\x0f\xa5\x05\xd0)\xb5\xa2jp.\xbd\xd7J\\\xfbVUt\xc5=\x18_zE\xe7\xb2u\xe0\\\x02\x1b\xcb\xa4\xca\xc4\xb4MS!\x15\x900#\xb8\xd6\x17J\x1c%T\xd5D\x96e\x86\x0e\x1a\x85\x9dl\xa4\x8d5Y\xcd\xb5:j+\xc0\xdb\x1e\xd9H\x19\xa4\x0f\x10\x87\x14\x97r\x8fu\x92\x8d\xbe\x91\x18\xc4\xe2\x81\xb8q>R\xedp\x81\x1d\x02\xf7\x14DB\xe1\xc7\x18-\xad\xa1[W\x96b\x87\xba \x0c\xc6\xc8\xc8E\x1e\x9a\xd0 \xb6\xa4\x03I6t}\xf3\xd4\xa9\x94\x02\xf9\x165JAh\xb0\x93\xb4\x94\x17O\xe8-\xc9\x1e\xdc)\xef\xac.\xa4X\x01\xa6\t\x01\xdf\xa1\xf6\x10\xa5\xe1\x84\xc0Y\xe02\x88:\x96\xe8n\xe4\x91\xd4$\xea\xb4B\xe9G\x81l~"\x93\xc8\x98\xbe\xd1\x96\t\xaa,\x19\xdd\xf8e5b\xc6\xd4*\x96\x14d\xd4\xc0%i\xa5\xe9\x9e\xd1\xde\x89\xe0\x1e"\x87=/J\x91(\x02\xd9\x1aq\x0f\x02\xd2\xb2\xa1r!U7\xe0 }\xb8\xd4\xa1\xc0\xbaN,\xf7\x85\x00\x19\x12^B\x8d!\xd0\xc3\x91\xae\x11\x16\xb4!\xd2\xa3\x18\x18\xba\xb9\x06\x15j\x86\x83\xc4\xba\xc0^\xbb@h\xe5\x17\xb4\x8d\x93\x07l\x9a-!\x80\xf7@\xb5\']\xc6z\x02N\xd7\xd1y$K\x89V\x89\xc3\xe7\x1d\xe4&\x19j\xdbI\x00Z[\x91qvm\xa0\xd9\x94\xe0X@m4\x8a\n\xcf\xc7\x8e+\xc3e\x8b6\x96\xc8\x02[\x81+\xc4\xbds%6\x8dR\xb3\xf3\xfa\x19\x12\x05\x84\xf3\x84\xfd\xc7\xd2\xca\xd6\xf4\x02\x18\x7f\xcdm\xf3i\'\xe9.\'\xd6~\x14Y\x83\xd1\xf6\xe3\xb7\x16\xa0\x83]&\xf3\xbb\x06H\xa4\xed\'\x0f\x80v*\x08\x90,\xed\xcb!\xb7h~\x9f\xe8\xc2\x83\xf9\xc8\xf0\x1f\xf0BEG\x00\xc1\x90t\xd0\x8d\x8bu\x87\x94\xc8\x0cJ\x8ao\x07X5@-\xa6\xf26\xc8s\x02L^c\xcf\x97\x00\x162\xa7\x95\x84\\G\x0b\xcc\x07RKq\x05\xf1H\xd3\x02\xd8\x88n[\x8a[\xe7=\xfdh\x8f\xd1\xb7\xad\xff\xadu\x9a\xca\x86\xd4\xbfS\x16C\x07*6u*\xd0\x03UC`\x7f=I\x19\x01\xf6\x170t*\x9dT\xca\xc1\xbb\xe8\nG\xbd\x91<\x80!i\xb6\x83\x92\x82,I\xfd\x18\x19\xe2?\xadD\x93\xddM\x1e\\\x01E\x96\xd4n\xad\x82>\x02r\x00\xc4\x0f\xe8\x0810\xea\x13\xd9\xa9SS\xcc\'\n\x91\x13=B\x88\xb9\x91\xb4E\x7f\x97\xd0\xe1\x00NW\x13\x14t"oX.\x11\xce\x06FB\x01P&\xbb\x96\xe8\x8f\xc5\xcc\xa1\xe1\x19\x0e\xf4\x15!\xbf\xed\x18\xa5\xa9PX\xb1&*}\'\xbd$\xf5\xbf\xf6\x01\xad\xce\x8b\xee\\\xa9\'\x1a$4\n_p\x12\x0e\x99\xaa<\xec.\xc4J\xfb\xa2\xd5D)\xec\x00U\xb4\x1bI\x1dBz\x80\xdcZ\xca\xe2\x91\x11\xb6\x17\x10\xd1\x93\xe8&\x0f\xf8w\xb6\xa1\xb0\xcf\x05\x82\xb2\xca\xff\x9c\xc2\x8c\x137*>1\xae\xc7\x1c\x1b\x0cQE6\xe7\x0bYA\xd2\xa00\xa9\x08\x98\xa1Y\x83\xe0.\xa7\x06\xa8J\xf2f\xc1\x8a\x9d\\\xeaH)\n\xa4c\xbd\xcc\xdc\x95\xa4\x94\xa7=2n\xa1\xaa<\xa5\xeb%;\xf2\x89\xc4\x05\x96\x05\x11F\xdf\xca\x02\x9bSt\x0b\xc9Q5Z\x82\x15$\xc6xN\xc1V\x9b\x1c\x1d\xca/Q\xf0\x18\xd9,]P\x07\x12\x8b\xa5\x84\xd2\xbd\xe5\xfa\xcb\xf7H\xff\n&_r9\x14\xdc\xaf\xe4\x02\xa2\xc2`\xd7\x9a4\x12\xdd\xa3\xb5\x8c\x00i\xa2\xban\x13\xa4\x83Z8\x88^\xa0\xecv2\xed\xe9pq\x8b\xd4\x94\x05q\xd9\xa6\xc6t\xf8p\x97\x90\x867\x05\xd5\'Bm(a#\x16\xae\xad\x0c5).\xbd\xa4\xe0\xcd\x99r[\x17\x82\x98\xb7\xd8O\n~\xb9%\xd8)\xc9\x8a\xf4[,\x9e\xc0NOZ*\x90\x92\xdcxW\x01\xb03\xb0\x01\xe6\xa0+\xe0\x08A\xf4\x14\x0e\x90v\xa0\x16\x81\x91L\xff\xd2W\x19\x82\xc7\xf6\x91\x98(t\x07m\xb8\xf0\x16)\xac\x97\xd6X\xdc\xc3k\xa7\x9b4\xf7\xbaa~^B`\xd1O\xc9\xd4q\xb2=\x15\xdc\x07\xc6\xf7\x99\x86\x9a\x11\xa2\xcb\xfc\x19\x96*\x13\x9cu,\xe7\xf6"_\xac\x95a\xfa\x8b\x9e\xf5\xb7\xec\x8cal\x91\xb2{\x07\x01#f\xf0\x06\x88(\xe8 \xdd\x05\xd2\x99s\xc3R\xa6\xb3\xf9\xb1De\x8f6\xc1=Q\xdfi\x07o\x92\x99\xe1\x0c:\x98:\xc5=`\xf5F\x1f\xb7i5\xe3\x14$Z\x91h\xc1\xe6^>\x818(\xc2*u\xd8\xf1z\xf2\x06\xc8\xcc\xa0f\xe9\xd1bC\xec\x0f\xa3ta\x1c4\x02\x8b\x06\xd7\xc8J\xf2\xa5\xbe=Dg\x90\xd8\x98\xd6\x1e(1\x81&F\xb2\x15\x15\xb5\x98\xc4\xf0G(I\xb4\xc7`6\xb7\'_CO\x00\xefx\xf8\xc6\rb\x03p\r\xe8\xa4\xd8\xde(Y%d\xe8\x16C\x93\xb5\\I\x00t7"\xcaR\x86\xcc\xa1\xfd\xd9U<\x89K4+\xd4y\xc9}\x1c\xf7\x16xoL,\xaf\x01\xe60x\x87\xe3\xe4O\xb1)\n\x1a\xa3\x06v\xdf\x8a\xf2\xdd%\x96\x92X^,\xd0S\x14\xbe%M.\xd7x\xdeB\x181&2\x12\x1c\x8d\xb8\xc21\x1f\xd9\xc99\xb8\xd75\xc9\xe0\x01\xeb\x05g\xdaDJ\x13\x08\xaa\xd4\xd6\x95\xa3\xe2\xf3\x1a`\xc38BY-l\xdb@\x1d\xe6\xac\xa5y\xfd\xfd(\xf8\x80\x9d\xe40\x84 &\xd2@\xd3`\x86\xa7v\x90\xc9\xd3\x17M7\x1c\x03q\x87\xd6\xe513u\x89\x04\x80\xa0?\x9d\x17\xb7>94\xf4\xc0nL\xeeOKI\xaa\xb4\x87Y\xae\xa8\xe6@\x0fj6`\x7f\xd0\xc1$\'\x0b\x0e\x05\xc9\xe0\x93\xa2\xa4\xe7T=\xc9_{\xf0!\x91\xcc\xa9\x19\xc8[\x9b+\xbf\x01\xc9\x82\xf4\x85npn\x80"\x8d\xbc\x049\xc1X\xef\x07R\xc2\x1aJ\xfa&o\x14$\r\xbel!r\xa4\x990VN6\x0c\x86\x8b\xca\xc7\x1b:I\x024\xe0\xeb\x05y\xac\x03NVG#!6\xd9\xbe&\xf6Kff.\xbe\xd91b]m(\x13\x9e\xf5\xb6j\x8f\xc3Kj\x7f\xf4.\xa5\x1a5[\xde\xe3,\xb8\xe2\xce{\x99\xae\xac\xafZ\xb1m5)\xf2\x84g\xa3-f\xce\xafatNgS8Y\xa6\xa9\xed,\xe7p\xc1>v\xfb=E\xb2F\xb1u\xd9\x0f0\xfc\xf3\xfe\xccg\x83\xe9\xd2$\x9c)t\x93\x84B<\x8eV\xa8\xcb\x9d\xfd\x991O}L\x1e\x82\\@\xee\xe2R\x1b\xce\xcb\xddA\xbb\xda\x8a]\xcb\xaa\xb3$JK\xe0:2\x8b\x81J46\xb0D;\x18\tbq\xb7\x1e.(\xcb\xf01M\xbdR\xe8x\xa9"\x98\xc2u\x80#\x996\x8bI\x7f\xe8\xea\x10&\xf0\xd1c\xf8\x93\xd1\xbcGk^\xa3\x1f \x89\x0f\xbd\xcf8\x11\xbd\xbb\xd5\x82M\x983\x07o\x836\xe4C8\xc2\x86WJ\xfe<k\x0bX\xfe\x14\x9dN|\x80L\x82\x1fKPh\x86\xfc\xa2\x99\xa7\x12\xda\xa1\'#\x92\xe3\xa4\xa3H\x8a%\xb9\x81\x11Hs\xb2M\xae&\x0c\x06\x05\xc7\xc4\xaaL\x17\x7fj\xe6\x82*`l\x96\x02\x9a\x926\xcdi\x16\xc3\x91>\x84Bz\xc8\xf5\x8a9\xd7y\xf1\x92\xd09Q\x17\x13\x07\xf7T^l$\xd2\x1f\x19\xc5\x95\x06h\xe3\x10\x93\x01\xf3\xea\xc7\xf3\x7ff\xeb\xc5\'C\x80\xe6V\xf6\xf6\xb9\x06\xf6\x02\x0eE\x88#]S\xa62\\@!\xb8\xd2k\xe2\xbf\xaa\x0c\x15\x18\x87\xf3\xd4\x9d"4t\xd7NH)\xb6\xaa\xb3\x10sD\x17.\x92%\x0c\xd7\x92\xc5_\x80\n\xae*\x90\x8d\x00i\xe0@\x95?\x98\xe6\x04\x1bP\x08\xc7\r\x14\x9bB\xc0\xd1\x90MG\xb0\xe4Y\xcb\xd8\xc1\'\x02\xbcR\x9c\x8br\xab(j\xddzG\xf3\xfb\xc5d\x1a\xbb&\x80\xaa\xc7\xd5%\xa2W^\xd8w\xcc%\xcc\x9f%\xaf\xf5\xc7X\xe2B\xe3\x06\x17\xa9\xbf\xf76\x17\xc87\x07\x0b\x0f\xe9\x04;\xdf\xb8\xa1]G\xc6\xa4\xe1\xb4>B\xbc\'\xa8b\x9b\xc6\xbe/cL\x00\xcc\xa53\xa9\x85f\n\t`N\xb1\x17\xbb1z\xad"u\xe4\xd1+t\xf4\x84\xf3\x92\xd3\xc7\xfb\x8fk\x08\x9f9\xcc4"\xce\xaep?\x88\tUo\xf0\x8c\x18-\xba\xe1\xac\x8e\x15\xd42\x9f\xd5\xb9A\xdb58\x07\xe5v9\x9f|/\xf4\'\xce\xb7\x81\x11uL\x88\xe5\xaal\x19\xc1\x17LN\x12\xc2\x18\xbf\x88t>\x08\xfc\xed\x03hJC/]\xf5\xc7a\xf7\x0c\x9c\xa7\r\xfd`\x80Kc\n\xe0\x90O\x1b!\xdc`0\xd9\xaa\xa6\xe1\xed\xef;\xf0\xae\x14\xce\xb7pQ(\xe1\xd6p\r\x17\x8c\xe71\xcd\xd6\xd3=Cl\x17\x00\x86n\x02W\xe7\xeb\x91~#?it3\xc9\xda\xce\x8d\r\xa8\xda\xb8N\x9aH\xd2\x1c\x1b]\xb7c1\x99I\x83\xf3\'\xea\xa7\xa5\xab[\xe2\n\x02\x81\x04?_\x98\xe0\xdb\xaf,\x0cF\x8c\xad\xdeT\xa1\x97x\xb2\xfb#p\xf8\xf2\x8cK%\xc3\xc1`b\xb4\x05\x96\x08\xb1\x8dcS\x83&\r\xce}:-\x8c\xbeMwc\xf8v\x9dL9An:\xb8\x1d\xbb\xa9\xb3{\xd2\xb8\xcb\x95\xbb\x87\x9fb\xdd\xdfJH\xdd\xe1\tF\xc6\x8eS\x88\x98\xf8z6\xbda\xa8\xed\x05\x9b\x0cn\x9fb\x11\xe9\x16\x86\x90\x87\x83\xc1\x99#\xef\x8f\xda\x96\x1e\x1a\xf4\x07X\xacm\x05\xe7\x94\xde\xfa{\t\xfb_]\xd6\xe1\xacQ\x98_\x9a\xbb0\x99hjW\xd4V\xe1\x88\x83\xde\xb7K\xa2\x80\xf6s8\tb\xc1t\x8a\xf3;\xb2W5\xe3ig\x0fm\xa5\xc8n\xf7vF2\x88\x86\x9fI\'O\xf4"\xcd\xcb\x1d\x85\xd1\x83\xb8\x8c\x04\xc3o\xad\xd2%\x9b\x91;^\x97\xb5\x0bq\xcc\x9db:\xdf\x17\xe9\xf0\xc10V[\xbeX8\x1c}&\xfd>\x05\x1d\x1c\xca4T\xb8\xbd\x9b\xee\x06\xf0\x18\xb31-!\x83\x17]3\xc5}?\xf8SN,\x16;\x12\xbco\\\xe5\xb2\xb38\xca(\xfe\xfa\xe2\xd0\x14\xe7?\xd4\xc9\xef-\x12\x18\xe14\xa0\xe9\x86\xd8\x08N\xcc\x809c\xfe\xe0=\x88\x84|\xed\xcaE\xce \xcas\xc2\xe5(\xaf\x1f\x1e(\xbe\xad \x90\xe9-\x07\xd0\x1bA \xdcW\x14W\xed\x1e{@\\;\\\xa9\xc3\x81G\xd

In [3]:
df = pd.read_csv("/content/Superservicios-Información_de_Accidentes_de_Origen_Eléctrico-Formato19_20260929.csv")

In [4]:
df.head()

,IDENTIFICADOR_EMPRESA,EMPRESA,FECHA,ANIO,TRIMESTRE,HORA,COD_DANE,DEPARTAMENTO,MUNICIPIO,CENTRO_POBLADO,...,TIPO_IDENTIFICACION,VINCULADO_EMPRESA,TIPO_VINCULACION,GRADO_ESCOLARIDAD,TIEMPO_VINCULACION,SECCION_EMPRESA,TIPO_LESION,ORIGEN_ACCIDENTE,CAUSA_ACCIDENTE,MEDIDAS
0,617.0,EMPRESAS MUNICIPALES DE CARTAGO S.A.S. E.S.P.,03/09/2011,2011,1,12:15,76147010,VALLE DEL CAUCA,CARTAGO,ZARAGOZA,...,C.C.,S,CONTRATISTA,BACHILLER,120,Operación - Distribución,Tetanización,Fallas de aislamiento,Sobrecarga,Utilizar; debidamente los equipos de protecciï...
1,617.0,EMPRESAS MUNICIPALES DE CARTAGO S.A.S. E.S.P.,09/09/2010,2010,3,09:55,76147000,VALLE DEL CAUCA,CARTAGO,CARTAGO,...,C.C.,S,CONTRATISTA,BÁSICA PRIMARIA,12,Labores de Comercialización,Quemaduras,Malos contactos,Equipo defectuoso,SE IMPLEMENTARA UN PROTOCOLO DE TRABAJO SEGURO
2,3370.0,EMPRESA DE ENERGIA DE CASANARE SA ESP,09/05/2015,2015,3,09:15,85263000,CASANARE,PORE,PORE,...,C.C.,S,CONTRATISTA,TÉCNICO,6,Operación - Distribución,Quemaduras,Fallas de operación,Contacto Directo,Instalacion correcta puesta a tierra Reforzar ...
3,23442.0,COMPAÑIA ENERGETICA DE OCCIDENTE S.A.S. E.S.P.,11/27/2014,2014,4,11:40,19698020,CAUCA,SANTANDER DE QUILICHAO,QUINAMAYO,...,C.C.,S,CONTRATISTA,BÁSICA PRIMARIA,2,Otro - Distribución,Muerte,Violación de distancias de seguridad,Contacto Indirecto,Realizar un programa de capacitacion de identi...
4,617.0,EMPRESAS MUNICIPALES DE CARTAGO S.A.S. E.S.P.,09/18/2014,2014,3,11:45,76147000,VALLE DEL CAUCA,CARTAGO,CARTAGO,...,C.C.,S,PLANTA,BÁSICA PRIMARIA,215,Operación - Distribución,Quemaduras,Fallas de mantenimiento,Arcod Eléctricos,CAMBIO DE 2 CORTA CIRCUITOS PODA DE ARBOLES Y ...

In [5]:
url = "https://github.com/Starleen1996/analisis_datos_curso/blob/main/Superservicios-Informaci%C3%B3n_de_Accidentes_de_Origen_El%C3%A9ctrico-Formato19_20260929.csv"

In [7]:
raw_url = url.replace("github.com", "raw.githubusercontent.com").replace("/blob/", "/")
df1 = pd.read_csv(raw_url)

In [8]:
df1.head()

,IDENTIFICADOR_EMPRESA,EMPRESA,FECHA,ANIO,TRIMESTRE,HORA,COD_DANE,DEPARTAMENTO,MUNICIPIO,CENTRO_POBLADO,...,TIPO_IDENTIFICACION,VINCULADO_EMPRESA,TIPO_VINCULACION,GRADO_ESCOLARIDAD,TIEMPO_VINCULACION,SECCION_EMPRESA,TIPO_LESION,ORIGEN_ACCIDENTE,CAUSA_ACCIDENTE,MEDIDAS
0,617.0,EMPRESAS MUNICIPALES DE CARTAGO S.A.S. E.S.P.,03/09/2011,2011,1,12:15,76147010,VALLE DEL CAUCA,CARTAGO,ZARAGOZA,...,C.C.,S,CONTRATISTA,BACHILLER,120,Operación - Distribución,Tetanización,Fallas de aislamiento,Sobrecarga,Utilizar; debidamente los equipos de protecciï...
1,617.0,EMPRESAS MUNICIPALES DE CARTAGO S.A.S. E.S.P.,09/09/2010,2010,3,09:55,76147000,VALLE DEL CAUCA,CARTAGO,CARTAGO,...,C.C.,S,CONTRATISTA,BÁSICA PRIMARIA,12,Labores de Comercialización,Quemaduras,Malos contactos,Equipo defectuoso,SE IMPLEMENTARA UN PROTOCOLO DE TRABAJO SEGURO
2,3370.0,EMPRESA DE ENERGIA DE CASANARE SA ESP,09/05/2015,2015,3,09:15,85263000,CASANARE,PORE,PORE,...,C.C.,S,CONTRATISTA,TÉCNICO,6,Operación - Distribución,Quemaduras,Fallas de operación,Contacto Directo,Instalacion correcta puesta a tierra Reforzar ...
3,23442.0,COMPAÑIA ENERGETICA DE OCCIDENTE S.A.S. E.S.P.,11/27/2014,2014,4,11:40,19698020,CAUCA,SANTANDER DE QUILICHAO,QUINAMAYO,...,C.C.,S,CONTRATISTA,BÁSICA PRIMARIA,2,Otro - Distribución,Muerte,Violación de distancias de seguridad,Contacto Indirecto,Realizar un programa de capacitacion de identi...
4,617.0,EMPRESAS MUNICIPALES DE CARTAGO S.A.S. E.S.P.,09/18/2014,2014,3,11:45,76147000,VALLE DEL CAUCA,CARTAGO,CARTAGO,...,C.C.,S,PLANTA,BÁSICA PRIMARIA,215,Operación - Distribución,Quemaduras,Fallas de mantenimiento,Arcod Eléctricos,CAMBIO DE 2 CORTA CIRCUITOS PODA DE ARBOLES Y ...

## EJERCICIO CON BD DE PRECIOS DE VUELOS

In [9]:
df_precios = pd.read_excel("/content/precios_vuelos.xlsx")

In [11]:
df_precios.head(10)

  Aerolinea  precios ida
0   Avianca       129500
1   Avianca       168395
2   Avianca       168395
3   Avianca       207300
4   Avianca       224700
5   Avianca       342658
6     Latam       368250
7     Latam       544925
8     Latam       575776
9     Latam       679857

In [12]:
df_precios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Aerolinea    10 non-null     object
 1   precios ida  10 non-null     int64
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

In [13]:
df_precios.describe()

         precios ida
count      10.000000
mean   340975.600000
std    196636.480681
min    129500.000000
25%    178121.250000
50%    283679.000000
75%    500756.250000
max    679857.000000

In [14]:
# MOSTRAS ULTIMAS FILAS DEL DATAFRAME
df_precios.tail()

  Aerolinea  precios ida
5   Avianca       342658
6     Latam       368250
7     Latam       544925
8     Latam       575776
9     Latam       679857

In [18]:
#CREAR UNA NUEVA COLUMNA PARAEL CALCULO TOTAL DE LOS TIQUETES PARA 2 PERSONAS
df_precios["Valor_Total_Ida"] = df_precios["precios ida"] * 2
df_precios

  Aerolinea  precios ida  Valor_Total_Ida
0   Avianca       129500           259000
1   Avianca       168395           336790
2   Avianca       168395           336790
3   Avianca       207300           414600
4   Avianca       224700           449400
5   Avianca       342658           685316
6     Latam       368250           736500
7     Latam       544925          1089850
8     Latam       575776          1151552
9     Latam       679857          1359714

## REALIZAR CALCULOS ESTADISTICOS

In [23]:
# Vamos a relaizar calculos estadisticos: Media,Mediana,Moda
print("La Media de los precios ida es: ", df_precios["precios ida"].mean())
print("La Mediana de los precios ida es: ", df_precios["precios ida"].median())
print("La Moda de los precios ida es: ", df_precios["precios ida"].mode())
print("El precio mimino es:", df_precios["precios ida"].min())
print("El precio maximo es:", df_precios["precios ida"].max())
print("La desviacion estandar es:", df_precios["precios ida"].std())
print("La varianza es:", df_precios["precios ida"].var())
print("El rango de los datos es:", df_precios["precios ida"].max() - df_precios["precios ida"].min())
print("La curtuosis es:", df_precios["precios ida"].kurtosis())
print("La asimetria es:", df_precios["precios ida"].skew)
print("El sesgo del precio de ida es:", df_precios['precios ida'].skew())

La Media de los precios ida es:  340975.6
La Mediana de los precios ida es:  283679.0
La Moda de los precios ida es:  0    168395
Name: precios ida, dtype: int64
El precio mimino es: 129500
El precio maximo es: 679857
La desviacion estandar es: 196636.48068069387
La varianza es: 38665905534.48889
El rango de los datos es: 550357
La curtuosis es: -1.0933460873312573
La asimetria es: <bound method Series.skew of 0    129500
1    168395
2    168395
3    207300
4    224700
5    342658
6    368250
7    544925
8    575776
9    679857
Name: precios ida, dtype: int64>
El sesgo del precio de ida es: 0.6698121062087512

In [24]:
df_precios['Valor_Total_Ida']

0     259000
1     336790
2     336790
3     414600
4     449400
5     685316
6     736500
7    1089850
8    1151552
9    1359714
Name: Valor_Total_Ida, dtype: int64

In [26]:
df_precios['Aerolinea'].mode()

0    Avianca
Name: Aerolinea, dtype: object